language: node_js
git:
  depth: 1
cache: npm
matrix:
  include:
    - node_js: "8"
      script: npm run pretest
      env: CI=pretest
    - node_js: "8"
      script: npm run jest -- --runInBand  --coverage
      env: CI=coverage
    - node_js: "10"
      script: npm run jest -- --runInBand
      env: CI=tests 10
    - node_js: "12"
      script: npm run jest -- --runInBand
      env: CI=tests 12
after_success:
  - if [ "$CI" = "coverage" ]; then npm run coveralls; fi
